# version: '3.8'

# services:
#   dynamodb-local:
#     image: instructure/dynamo-local-admin
#     ports:
#       - "8000:8000"

#   backend:
#     build:
#       context: .
#       dockerfile: backend/Dockerfile
#     volumes:
#       - ./backend:/app/backend
#       - /app/node_modules
#     ports:
#       - "5001:5001"
#     depends_on:
#       - dynamodb-local
#     environment:
#       - AWS_REGION=us-east-1
#       - DYNAMODB_ENDPOINT=http://dynamodb-local:8000

#   frontend:
#     build:
#       context: .
#       dockerfile: frontend/Dockerfile
#     volumes:
#       - ./frontend:/app/frontend
#       - /app/node_modules
#     ports:
#       - "4000:4000"
#     depends_on:
#       - backend

version: '3.8'

services:
  dynamodb-local:
    image: instructure/dynamo-local-admin
    ports:
      - "8000:8000"

  app:
    build:
      context: .
      dockerfile: Dockerfile # Use the Dockerfile in the root of your monorepo
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4000:4000"  # Frontend port
      - "5001:5001"  # Backend port
    depends_on:
      - dynamodb-local
    environment:
      - AWS_REGION=us-east-1
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
      - NODE_ENV=development