version: '3.8'

services:
  dynamodb-local:
    image: instructure/dynamo-local-admin
    ports:
      - "8000:8000"
    environment:
      - AWS_REGION=us-east-1
      - DYNAMODB_ENDPOINT=http://localhost:8000
    volumes:
      - dynamodb_data:/home/dynamodblocal/dynamodb_data
volumes:
  dynamodb_data: